version: "3"
services:
  stock_app:
    build: 
      context: "./src"
    working_dir: /app
    restart: on-failure
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "8000:80"
    volumes:
       - ./src:/app
    networks:
      - stock
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.5
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: watchlist
    volumes:
      - ./src/db/tables.sql:/docker-entrypoint-initdb.d/tables.sql
    ports:
      - "5432:5432"
    networks:
      - stock
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  stock: